version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: codifya_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: codifya_user
      POSTGRES_PASSWORD: codifya_password
      POSTGRES_DB: codifya_ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 